// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcu1coIyFBZktLhjDBAkUGYSdfJYQXk2o',
    appId: '1:392533223139:web:5204dbd6c3752c0e4607d6',
    messagingSenderId: '392533223139',
    projectId: 'laundry-69cf1',
    authDomain: 'laundry-69cf1.firebaseapp.com',
    storageBucket: 'laundry-69cf1.appspot.com',
    measurementId: 'G-B6HB614GVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB_N1pbGCKYiB5ROOUO4Y9-RSaS6gq2TY',
    appId: '1:392533223139:android:8c41db0e6c5e71aa4607d6',
    messagingSenderId: '392533223139',
    projectId: 'laundry-69cf1',
    storageBucket: 'laundry-69cf1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5xvjvrHk5ThBkC3LbY6ce9r1E0aNhQe4',
    appId: '1:392533223139:ios:0f5edea5fe7e8b534607d6',
    messagingSenderId: '392533223139',
    projectId: 'laundry-69cf1',
    storageBucket: 'laundry-69cf1.appspot.com',
    iosBundleId: 'com.example.laundryEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5xvjvrHk5ThBkC3LbY6ce9r1E0aNhQe4',
    appId: '1:392533223139:ios:79e5bf2358d8fa264607d6',
    messagingSenderId: '392533223139',
    projectId: 'laundry-69cf1',
    storageBucket: 'laundry-69cf1.appspot.com',
    iosBundleId: 'com.example.laundryEase.RunnerTests',
  );
}
